name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
        # TODO: 
        # - x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cross
        run: cargo install cross

      - name: Build for ${{ matrix.target }}
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          # Dateiname zusammensetzen
          OUT_NAME="stapler-${{ matrix.target }}${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}"
          echo "OUT_NAME=$OUT_NAME" >> $GITHUB_ENV

          echo "==> Dateien in release-Ordner:"
          ls -al target/${{ matrix.target }}/release/

          # Abhängig vom Zielsystem umbenennen
          if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]; then
            mv target/${{ matrix.target }}/release/stapler.exe "$OUT_NAME"
          else
            # Falls du sicher bist, dass die Datei schlicht 'stapler' heißt:
            mv target/${{ matrix.target }}/release/stapler "$OUT_NAME"
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist/${{ env.OUT_NAME }}
          path: dist/${{ env.OUT_NAME }}

      

  release:
    needs: build
    runs-on: ubuntu-latest
    # Läuft nur für Tags, die mit 'v' beginnen
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          # Lädt alle hochgeladenen Artefakte herunter
          path: dist

      - name: List artifacts
        run: ls -R dist

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This release was automatically generated by GitHub Actions.
          files: dist/*
          fail_on_unmatched_files: true
