name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose

  benchmarker-2-files:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmarks
        run: |
          set -e 
          export CRITERION_MAX_FILES=2
          for _ in {1..4}; do
            cargo bench
          done
          cargo bench --verbose

  benchmarker-10-files:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmarks
        run: |
          set -e 
          export CRITERION_MAX_FILES=10
          for _ in {1..4}; do
            cargo bench
          done
          cargo bench --verbose

  benchmarker-100-files:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmarks
        run: |
          set -e 
          export CRITERION_MAX_FILES=100
          for _ in {1..4}; do
            cargo bench
          done
          cargo bench --verbose

  benchmarker-500-files:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmarks
        run: |
          set -e 
          export CRITERION_MAX_FILES=500
          for _ in {1..4}; do
            cargo bench
          done
          cargo bench --verbose

  benchmarker-1000-files:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmarks
        run: |
          set -e 
          export CRITERION_MAX_FILES=1000
          for _ in {1..4}; do
            cargo bench
          done
          cargo bench --verbose
